import dotenv from "dotenv";
import { FIREBASE_CONFIG_VAR } from "firebase-admin/lib/app/lifecycle";
dotenv.config();

export const config = {
	port: process.env.PORT ?? 8000,
	NODE_ENV: "development",
	BASE_URL: process.env.BASE_URL,
	"api-prefix": "api/",
	POSTGRES_HOST: process.env.POSTGRES_HOST,
	POSTGRES_PORT: process.env.POSTGRES_PORT,
	POSTGRES_USER: process.env.POSTGRES_USER,
	POSTGRES_PASSWORD: process.env.POSTGRES_PASSWORD,
	POSTGRES_DB: process.env.POSTGRES_DB,
	POSTGRES_URL: process.env.POSTGRES_URL,

	JWT_SECRET: process.env.JWT_SECRET,

	SMTP_SERVICE: process.env.SMTP_SERVICE,
	SMTP_PASSWORD: process.env.SMTP_PASSWORD,
	SMTP_PORT: process.env.SMTP_PORT,
	SMTP_USER: process.env.SMTP_USER,
	SMTP_HOST: process.env.SMTP_HOST,
	SMTP_FROM_USER: process.env.SMTP_FROM_USER,

	REDIS_URL: process.env.REDIS_URL,
	REDIS_HOST: process.env.REDIS_HOST,
	REDIS_PORT: process.env.REDIS_PORT || 6379,
	REDIS_PASSWORD: process.env.REDIS_PASSWORD,

	SECRET_TOKEN: process.env.SECRET_TOKEN,

	MAIN_DB_URI: process.env.MONGODB_MAIN_URL,
	METRICS_DB_URI: process.env.MONGODB_METRICS_URL,

	AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
	AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
	AWS_REGION: process.env.AWS_REGION,
	AWS_BUCKET_NAME: process.env.AWS_BUCKET_NAME,

	FIREBASE_CREDENTIALS_PATH: process.env.FIREBASE_CREDENTIALS_PATH,
	FRONTEND_URL: process.env.FRONTEND_URL,
	WEBSOCKET_PORT: process.env.WEBSOCKET_PORT,

	TWITTER_CLIENT_ID: process.env.TWITTER_CLIENT_ID,
	TWITTER_CLIENT_SECRET: process.env.TWITTER_CLIENT_SECRET,
	TWITTER_REDIRECT_URI: process.env.TWITTER_REDIRECT_URI,
	TWITTER_BEARER_TOKEN: process.env.TWITTER_BEARER_TOKEN,
	TWITTER_ACCESS_TOKEN: process.env.TWITTER_ACCESS_TOKEN,
	TWITTER_STATE: process.env.TWITTER_STATE,

	CODE_CHALLENGE: process.env.CODE_CHALLENGE,
	CODE_CHALLENGE_METHOD: process.env.CODE_CHALLENGE_METHOD,

	SESSION_SECRET: process.env.SESSION_SECRET || "just plain secret",
	PRODUCTION_SESSION_SECRET: process.env.PRODUCTION_SESSION_SECRET,

	GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
	GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,

	REDIRECT_URI: process.env.REDIRECT_URI,
	YOUTUBE_API_SCOPE: process.env.YOUTUBE_API_SCOPE,

	FACEBOOK_APP_ID: process.env.FACEBOOK_APP_ID,
	FACEBOOK_APP_SECRET: process.env.FACEBOOK_APP_SECRET,
	FACEBOOK_REDIRECT_URI: process.env.FACEBOOK_REDIRECT_URI,

	INSTAGRAM_APP_ID: process.env.INSTAGRAM_APP_ID,
	INSTAGRAM_APP_SECRET: process.env.INSTAGRAM_APP_SECRET,
	INSTAGRAM_REDIRECT_URL: process.env.INSTAGRAM_REDIRECT_URI,
};
