import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../globals.css";
import { Roboto } from "next/font/google";

import { redirect } from "next/navigation";
import getCurrentUserData from "@/utils/getCurrentUserData";
import { Toaster } from "@/components/ui/toaster";
import { SideBarLayout } from "@/components/authorized/influencer/side-bar/SideBar.component";

const roboto = Roboto({
	weight: ["100", "300", "400", "500", "700", "900"],
	subsets: ["latin"],
});

const geistSans = localFont({
	src: "../../fonts/GeistMonoVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "../../fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const userData = await getCurrentUserData();
	if (!userData) {
		redirect("/login");
	}
	if (userData?.role === "Brand") {
		redirect("/brand/dashboard");
	}
	return (
		<section
			className={`${geistSans.variable} ${geistMono.variable} antialiased ${roboto.className}`}
		>
			<SideBarLayout>{children}</SideBarLayout>
			<Toaster />
		</section>
	);
}
